### PR TITLE
Update bugs.html

### PR DESCRIPTION
**Pull request by tjhorner**

### CODE REVIEW

**Comment by Syrexide** [comment]
Yes they do.

**Comment by tjhorner** [comment]
No they don't.

**Comment by Syrexide** [comment]
Maybe for your friend, but not for me. Or my sister's phone.

**Comment by tjhorner** [comment]
re-open

**Comment by Syrexide** [comment]
didn't say i could reclose it

**Comment by tjhorner** [comment]
re-open and keep open

**Comment by tjhorner** [comment]
are we using github correctly

**Comment by Syrexide** [comment]
probably not

**Comment by tjhorner** [comment]
yeah

**Comment by tjhorner** [comment]
Please pull

**Comment by wc1202** [comment]
invalid wontfix

**Pull request closed without merging**
